### ISSUE TITLE
discussion sur les cartes visibles

### ISSUE THREAD

**Issue by vinber** [osm-fr/osm-fr-front-map#14]
début de discussion ici https://forum.openstreetmap.fr/t/site-internet-public-styles-thematiques-erreur-de-libelle/18511/2

peut-être mettre les 3 langues et sortir stamen ?

**Comment by bristow** [comment]
Les 2 autres y sont dans le fichier mais sont commentées : https://github.com/osm-fr/osm-fr-front-map/blob/master/assets/leaflet-providers.js#L280

Pour virer Stamen, suffit de commenter je suppose.

Je peux faire le nécessaire mais je suis pas sûr que cela suffise ;)

C'était @althio qui avait fait le nécessaire :)

**Comment by bristow** [comment]
Bon, j'ai fait une pull request, @althio doit me la valider. Cela fonctionne chez moi ;)

https://github.com/osm-fr/osm-fr-front-map/pull/15

**Comment by vinber** [comment]
Merci

**Comment by nlehuby** [comment]
c'est fait, merci à vous.
