### ISSUE TITLE
version mobile : simplication de la carte

### ISSUE THREAD

**Issue by althio** [osm-fr/osm-fr-front-map#2]
- retirer le cadre de choix des fonds de carte sur les petits écrans ?
- changer style du cadre de choix des fonds de carte sur les petits écrans ?
- ... ?

![www openstreetmap fr_carte_responsive](https://user-images.githubusercontent.com/9863567/51739261-529edb00-2091-11e9-9542-fedc3f91b033.png)

**Comment by althio** [comment]
je travaille dessus et j'essaie de proposer quelque chose

**Comment by althio** [comment]
première modification (hors de ce répertoire, mais notée ici pour information et archive) : 

> ajout de code CSS pour la gestion de la iframe qui porte la carte, dans le [module wordpress](https://www.openstreetmap.fr/wp-admin/customize.php?url=https%3A%2F%2Fwww.openstreetmap.fr%2F) :arrow_right: `CSS additionnel`

> objectif : changer la taille de la iframe en fonction de la taille disponible, et supprimer l'affichage de la carte si l'écran est vraiment trop petit.
```
.iframe_map {
    border: 1px solid black;
    overflow: hidden;
    width: 100%;
    height: 60vh;
    max-height: 640px;
}
@media only screen and (orientation: portrait) {
  /* For rotated screens: */
  .iframe_map {
    width: 80vw;
    height: 80vh;
  }
}
@media only screen and (max-width: 556px) {
  /* For small screens: */
  .iframe_map {
    width: 80vw;
    height: 80vh;
  }
}
@media only screen and (max-width: 400px) and (max-height: 300px),
 only screen and (max-width: 300px),
 only screen and (max-height: 200px) {
  /* For very small screens: */
  .iframe_map {
    display: none;
  }
}
```

**Comment by althio** [comment]
Tests en cours, visibles sur https://althio.github.io/osm-fr-front-map/

...des commentaires ?

**Comment by nlehuby** [comment]
Des captures d'écran seraient bienvenues, comme le rendu final dépend beaucoup de la taille de l'écran sur lequel c'est testé.
L'idée est de réduire la hauteur du sélecteur de fonds afin qu'on voit mieux la carte c'est ça ?

**Comment by althio** [comment]
> L'idée est de réduire la hauteur du sélecteur de fonds afin qu'on voit mieux la carte c'est ça ?

Oui, pour voir mieux la carte, modifier le sélecteur de fonds
- adapter la hauteur
- adapter la largeur
- ou faire disparaître

> Des captures d'écran seraient bienvenues, comme le rendu final dépend beaucoup de la taille de l'écran sur lequel c'est testé.

Je gardais l'idée de faire des captures, mais avec un site de test https://althio.github.io/osm-fr-front-map/ tu peux voir l'effet sur toutes les tailles de fenêtre et d'écran que tu souhaites. (et comparer en direct avec https://osm-fr.github.io/osm-fr-front-map/)

**Comment by althio** [comment]
Quelques captures pour des cas "typiques", en situation sur la page du site

appareil | état actuel | test en cours
---|---|---
smartphone (portait) | ![www openstreetmap fr_ iphone_6_7_8](https://user-images.githubusercontent.com/9863567/52849240-dbe58280-3110-11e9-9174-2ad45e5b4024.png) | ![www openstreetmap fr_ iphone_6_7_8 _ r](https://user-images.githubusercontent.com/9863567/52849245-dc7e1900-3110-11e9-8499-4e1b2a021497.png)
smartphone (paysage) | ![www openstreetmap fr_ iphone_6_7_8_landscape](https://user-images.githubusercontent.com/9863567/52849241-dbe58280-3110-11e9-9d5f-6d21171b2110.png) | ![www openstreetmap fr_ iphone_6_7_8_landscape _ r](https://user-images.githubusercontent.com/9863567/52849242-dc7e1900-3110-11e9-8dbc-243609399593.png)
tablette | ![www openstreetmap fr_ ipad](https://user-images.githubusercontent.com/9863567/52849237-dbe58280-3110-11e9-9a7f-ee6b0c17522e.png) | ![www openstreetmap fr_ ipad _ r](https://user-images.githubusercontent.com/9863567/52849239-dbe58280-3110-11e9-8498-1cf42a89a2a6.png)
ordinateur | ![www openstreetmap fr_ laptop](https://user-images.githubusercontent.com/9863567/52849246-dc7e1900-3110-11e9-8e4d-b58c0ad61559.png) | ![www openstreetmap fr_ laptop _ r](https://user-images.githubusercontent.com/9863567/52849247-dc7e1900-3110-11e9-8f90-28a250e9fddd.png)

**Comment by althio** [comment]
Alors, quoi qu'on fait ?
PR et on déploie ? ou bien ?

**Comment by nlehuby** [comment]
oui, let's go :rocket:
