### ISSUE TITLE
attribution sur les cartes

### ISSUE THREAD

**Issue by althio** [osm-fr/osm-fr-front-map#3]
Je pense qu'on pourrait être "exemplaire" et mettre des attributions longues et explicites.
Si possible, mettre des attributions plus longues pour les grands écrans et plus courtes pour les appareils mobiles.

- exemple de nouvelle version longue et explicite : 
> données par [les contributeurs OpenStreetMap](http://www.openstreetmap.org/copyright), sous licence ODbL ♥ [Faire un don](https://donate.openstreetmap.org/)
> fond de carte par [OpenStreetMap France](http://www.openstreetmap.fr/mentions-legales/), sous [licence CC BY-SA](http://creativecommons.org/licenses/by-sa/2.0/fr/)
> affichage par [Leaflet](http://leafletjs.com/)

- exemple de nouvelle version courte et imagée : 
> :information_source: © [les contributeurs OpenStreetMap](http://www.openstreetmap.org/copyright) :world_map: [OSM-FR](http://www.openstreetmap.fr/mentions-legales/) :rocket: [Leaflet](http://leafletjs.com/)

Vos avis ?

cc @jocelynj @nlehuby @cquest @yohanboniface @vinber

---

par exemple sur le rendu OSM-FR:
- actuellement sur l'accueil http://www.openstreetmap.fr/ : 

> [Leaflet](http://leafletjs.com/) | © Openstreetmap France | © [OpenStreetMap](http://www.openstreetmap.org/copyright) 

(avec liens pas toujours fonctionnels dans la frame)
- actuellement sur http://layers.openstreetmap.fr/ : 

> © Openstreetmap France | Données © [les contributeurs OpenStreetMap](http://www.openstreetmap.org/copyright)

- actuellement sur https://umap.openstreetmap.fr : 
> map data © [OpenStreetMap contributors](http://www.openstreetmap.org/copyright) under ODbL — About — Home
:arrow_right: 2 clics, About, Credits: 
Map background credits
**OSM-Fr** map data © OpenStreetMap contributors under ODbL
Powered by Leaflet and Django, glued by uMap project.

**Comment by althio** [comment]
Autre attribution à harmoniser : rendu humanitaire

* exemple de nouvelle version longue et explicite :
 
> données par [les contributeurs OpenStreetMap](http://www.openstreetmap.org/copyright), sous licence ODbL ♥ [Faire un don](https://donate.openstreetmap.org/)
> fond de carte par [Yohan Boniface](https://github.com/yohanboniface), sous [licence CC BY-SA](http://creativecommons.org/licenses/by-sa/2.0/fr/), hébergé par [OpenStreetMap France](http://www.openstreetmap.fr/mentions-legales/)
> affichage par [Leaflet](http://leafletjs.com/)

* exemple de nouvelle version courte et imagée :

> :information_source: © [les contributeurs OpenStreetMap](http://www.openstreetmap.org/copyright) :world_map: [Y. Boniface](https://github.com/yohanboniface) et [OSM-FR](http://www.openstreetmap.fr/mentions-legales/) :rocket: [Leaflet](http://leafletjs.com/)
 
Vos avis ? (bis :wink:)

cc @cquest @yohanboniface @vinber

---

* actuellement sur l'accueil http://www.openstreetmap.fr/ :

> - OpenStreetMap.HOT

> [Leaflet](http://leafletjs.com/) | © [OpenStreetMap](http://www.openstreetmap.org/copyright), Tiles courtesy of [Humanitarian OpenStreetMap Team](http://hot.openstreetmap.org/)
 
(avec liens pas toujours fonctionnels dans la frame)
 
* actuellement sur http://layers.openstreetmap.fr/ :

> * HOT-HDM (tile)
 
> calque © ybon | Données © [les contributeurs OpenStreetMap](http://www.openstreetmap.org/copyright)

* actuellement sur https://umap.openstreetmap.fr :

> :gb:|:fr: OSM humanitarian (OSM-FR) 

> :gb: map data © [OpenStreetMap contributors](http://www.openstreetmap.org/copyright) under ODbL - Tiles © HOT [— About]() [— Home]()
> :arrow_right: 2 clics, About, Credits:
> Map background credits
> **OSM humanitarian (OSM-FR)** map data © [OpenStreetMap contributors](http://www.openstreetmap.org/copyright) under ODbL - Tiles © HOT
> Powered by Leaflet and Django, glued by uMap project.

> :fr: map data © [OpenStreetMap contributors](http://www.openstreetmap.org/copyright) under ODbL - Tiles © HOT [— À propos]() [— Accueil]()
> :arrow_right: 2 clics, À propos, Crédits:
> Crédits pour le fond de carte
> **OSM humanitarian (OSM-FR)** map data © [OpenStreetMap contributors](http://www.openstreetmap.org/copyright) under ODbL - Tiles © HOT
> Propulsé par Leaflet et Django, mis en musique par uMap project.

**Comment by althio** [comment]
"besoins techniques" : 

- [x] affichage d'icônes dans le texte d'attribution
- [x] affichage sur plusieurs lignes du texte d'attribution
- [x] effet responsive : variation de l'attribution en fonction de la taille d'affichage

**Comment by althio** [comment]
je travaille dessus et j'essaie de proposer quelque chose

en cours : 
-  affichage d'icônes dans le texte d'attribution : ~~peut-être possible avec font-awesome (un peu lourd), pas encore abouti à un résultat~~ OK avec emoji unicode
-  affichage sur plusieurs lignes du texte d'attribution : OK, leaflet prend du html
-  effet responsive : variation de l'attribution en fonction de la taille d'affichage : OK par CSS

**Comment by nlehuby** [comment]
ce n'est que mon avis perso, tu en feras ce que tu veux mais je pense que c'est mieux si on peut éviter d'aller charger des librairies externes type font awesome pour afficher 2 picto en bas d'une iframe.
Ptet regarder du côté des emoji unicodes ?
* 🇫🇷 https://emojipedia.org/flag-for-france/
* 🗺️ https://emojipedia.org/world-map/
* ©️ https://emojipedia.org/copyright-sign/
* ❤️ https://emojipedia.org/heavy-black-heart/
* 🚀 https://emojipedia.org/rocket/

**Comment by althio** [comment]
version de test, travail en cours : https://althio.github.io/osm-fr-front-map/
- [x] textes plus longs et explicites, sur le même modèle pour toutes les couches
- [x] intégralité du texte en français (nom des couches et attributions)
- [x] attribution sur plusieurs lignes
  - données OSM + licence
  - tuiles + licence / hébergement
  - Leaflet
- [x] ajout de liens, et de textes pour les info-bulles au survol des liens
- [x] ajout d'icônes

en cours : 
- [x] variations (_responsive_) mettre des attributions plus longues pour les grands écrans et plus courtes pour les appareils mobiles.

![better-attribution](https://user-images.githubusercontent.com/9863567/52954600-e6ab4c00-338a-11e9-98e9-2aff84c50da4.png)

**Comment by althio** [comment]
une version prête, en test sur https://althio.github.io/osm-fr-front-map/

Quelques captures pour des cas "typiques", en situation sur la page du site

appareil | test en cours
---|---
smartphone (portait/paysage) | ![www openstreetmap fr_ iphone_6_7_8](https://user-images.githubusercontent.com/9863567/52963608-8a532700-33a0-11e9-8c8b-e96830f6b279.png) ![www openstreetmap fr_ iphone_6_7_8 _landscape](https://user-images.githubusercontent.com/9863567/52963609-8aebbd80-33a0-11e9-8d71-004db6babca4.png)
tablette | ![www openstreetmap fr_ ipad](https://user-images.githubusercontent.com/9863567/52963607-8a532700-33a0-11e9-9bc1-1d0447f018ae.png)
ordinateur | ![www openstreetmap fr_ laptop](https://user-images.githubusercontent.com/9863567/52963610-8aebbd80-33a0-11e9-80d2-9f3a03393837.png)

**Comment by nlehuby** [comment]
ça fait bcp de picto quand même non ?

**Comment by althio** [comment]
> ça fait bcp de picto quand même non ?

Oui, j'ai chargé avec tout ce qui me semblait possible et présentant un intérêt.
Et il faut faire un choix, dans les liens et donc dans les pictos, qu'on souhaite conserver ou éliminer ou changer de place, en fonction des tailles d'affichage.

Ce sera plus simple dans ce sens-là : y'a plus qu'à commenter/supprimer des lignes.

**Comment by althio** [comment]
j'ai tripatouillé quelques modifications, la version en cours de test est un peu plus légère au niveau affichage (en évitant les pictos successifs).
en test sur https://althio.github.io/osm-fr-front-map/

Si ça convient, je mets à jour PR #7

**Comment by althio** [comment]
> une version prête, en test sur https://althio.github.io/osm-fr-front-map/

Mise à jour des captures
 
appareil | test en cours
---|---
smartphone (portait/paysage) | ![www openstreetmap fr_ iphone_6_7_8](https://user-images.githubusercontent.com/9863567/53000818-80c1d180-3429-11e9-92fc-5869199cf671.png) ![www openstreetmap fr_ iphone_6_7_8_landscape](https://user-images.githubusercontent.com/9863567/53000819-815a6800-3429-11e9-8620-d4bdb3e8f9d3.png)
tablette | ![www openstreetmap fr_ ipad](https://user-images.githubusercontent.com/9863567/53000817-80c1d180-3429-11e9-9c8a-5d9f4767d53c.png)
ordinateur | ![www openstreetmap fr_ laptop](https://user-images.githubusercontent.com/9863567/53000820-815a6800-3429-11e9-92e3-b75e986bb4db.png)
