### ISSUE TITLE
choix du nom de la couche humanitaire

### ISSUE THREAD

**Issue by althio** [osm-fr/osm-fr-front-map#4]
changer pour "humanitaire"/"humanitarian" ?

**Comment by nlehuby** [comment]
`Humanitarian` me parait bien, et c'est aussi ce qu'il y a dans l'attribution.

**Comment by althio** [comment]
> `Humanitarian` me parait bien, et c'est aussi ce qu'il y a dans l'attribution.

oui d'accord avec ça mais je vais changer les attributions :stuck_out_tongue_winking_eye: 

pour franciser l'ensemble au passage, je préfère un peu `humanitaire` à `humanitarian`
... et c'est aussi ce qu'il y a dans nom de couche sur http://tile.openstreetmap.fr/ à l'heure actuelle :wink: 

en tout cas ce sera inclus dans le package des modifications à venir pour toutes les attributions et noms de couches.
