### ISSUE TITLE
erreurs 503 sur osm_fr "fonds-de-carte"

### ISSUE THREAD

**Issue by Cyrille37** [osm-fr/osm-fr-front-map#9]
Salut

La carte sur la page https://www.openstreetmap.fr/fonds-de-carte/ ne fonctionne pas à cause d'erreurs 503 depuis github:

![image](https://user-images.githubusercontent.com/368965/78672997-c5385700-78e1-11ea-83be-dda88a40960d.png)

**Comment by Cyrille37** [comment]
Bon, faut patienter : 

> GitHub Pages is temporarily down for maintenance.

**Comment by Cyrille37** [comment]
TB voilà, ça refonctionne :-)

**Comment by jfm72** [comment]
Bonjour,
Le fond de carte Hydda est hs, j'ai modifié ui.js, j'ai bon?

**Comment by nlehuby** [comment]
Hello,

https://github.com/osm-fr/osm-fr-front-map/blob/master/assets/leaflet-providers.js#L295 plutôt

**Comment by jfm72** [comment]
le serveur serait hs:
https://help.openstreetmap.org/questions/68610/hydda-map-tiles-not-working
